env = Environment()
env.Replace(CXXFLAGS=['-O2','-Wall','-ansi','-pedantic', '-std=c++11',
                      '-I/usr/include/x86_64-linux-gnu/qt5/QtGui',
                      '-I/usr/include/x86_64-linux-gnu/qt5'])
env.Replace(LIBS=['-lQt5Gui', '-lQt5Widgets', '-lQt5Core'])
env.SharedLibrary('pyphyc', ['pyphyc.cpp'])
